window.PLANNER_STORES = [
  {
    "id": "SW1X7XL-1",
    "region": "South East",
    "postcode": "SW1X 7XL",
    "postcodeKey": "SW1X7XL",
    "retailerGroup": "Indies",
    "retailer": "Tekzone S&V",
    "storeName": "London Knightsbridge Harrods",
    "name": "Tekzone S&V - London Knightsbridge Harrods",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.499445,
    "lon": -0.16321,
    "adminDistrict": "Kensington and Chelsea",
    "county": "",
    "country": "England"
  },
  {
    "id": "W1A1AB-2",
    "region": "South East",
    "postcode": "W1A 1AB",
    "postcodeKey": "W1A1AB",
    "retailerGroup": "Indies",
    "retailer": "Tekzone S&V",
    "storeName": "Selfridges Oxford St",
    "name": "Tekzone S&V - Selfridges Oxford St",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.514587,
    "lon": -0.152814,
    "adminDistrict": "Westminster",
    "county": "",
    "country": "England"
  },
  {
    "id": "CR04XL-3",
    "region": "South East",
    "postcode": "CR0 4XL",
    "postcodeKey": "CR04XL",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Croydon",
    "name": "Currys - Croydon",
    "visitsPerQuarter": 6,
    "status": "Attack",
    "sdStore": "No",
    "lat": 51.373547,
    "lon": -0.119544,
    "adminDistrict": "Croydon",
    "county": "",
    "country": "England"
  },
  {
    "id": "NW26LW-4",
    "region": "South East",
    "postcode": "NW2 6LW",
    "postcodeKey": "NW26LW",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Staples Corner",
    "name": "Currys - Staples Corner",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.569521,
    "lon": -0.228494,
    "adminDistrict": "Barnet",
    "county": "",
    "country": "England"
  },
  {
    "id": "RH117XN-5",
    "region": "South East",
    "postcode": "RH11 7XN",
    "postcodeKey": "RH117XN",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Crawley",
    "name": "Currys - Crawley",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.132471,
    "lon": -0.187953,
    "adminDistrict": "Crawley",
    "county": "West Sussex",
    "country": "England"
  },
  {
    "id": "BN37EU-6",
    "region": "South East",
    "postcode": "BN3 7EU",
    "postcodeKey": "BN37EU",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Brighton & Hove",
    "name": "Currys - Brighton & Hove",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 50.837604,
    "lon": -0.188192,
    "adminDistrict": "Brighton and Hove",
    "county": "",
    "country": "England"
  },
  {
    "id": "ME59SQ-7",
    "region": "South East",
    "postcode": "ME5 9SQ",
    "postcodeKey": "ME59SQ",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Medway",
    "name": "Currys - Medway",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.352213,
    "lon": 0.507123,
    "adminDistrict": "Medway",
    "county": "",
    "country": "England"
  },
  {
    "id": "SL15PS-8",
    "region": "South East",
    "postcode": "SL1 5PS",
    "postcodeKey": "SL15PS",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Slough",
    "name": "Currys - Slough",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.517338,
    "lon": -0.630873,
    "adminDistrict": "Slough",
    "county": "",
    "country": "England"
  },
  {
    "id": "GU11AJ-9",
    "region": "South East",
    "postcode": "GU1 1AJ",
    "postcodeKey": "GU11AJ",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Guildford",
    "name": "Currys - Guildford",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.248841,
    "lon": -0.578735,
    "adminDistrict": "Guildford",
    "county": "Surrey",
    "country": "England"
  },
  {
    "id": "KT34PA-10",
    "region": "South East",
    "postcode": "KT3 4PA",
    "postcodeKey": "KT34PA",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "New Malden",
    "name": "Currys - New Malden",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.398971,
    "lon": -0.247959,
    "adminDistrict": "Kingston upon Thames",
    "county": "",
    "country": "England"
  },
  {
    "id": "SE151LA-11",
    "region": "South East",
    "postcode": "SE15 1LA",
    "postcodeKey": "SE151LA",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Old Kent Road",
    "name": "Currys - Old Kent Road",
    "visitsPerQuarter": 6,
    "status": "Attack",
    "sdStore": "No",
    "lat": 51.483628,
    "lon": -0.064911,
    "adminDistrict": "Southwark",
    "county": "",
    "country": "England"
  },
  {
    "id": "GU148BL-12",
    "region": "South East",
    "postcode": "GU14 8BL",
    "postcodeKey": "GU148BL",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Farnborough",
    "name": "Currys - Farnborough",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.307447,
    "lon": -0.748887,
    "adminDistrict": "Rushmoor",
    "county": "Hampshire",
    "country": "England"
  },
  {
    "id": "TW89DE-13",
    "region": "South East",
    "postcode": "TW8 9DE",
    "postcodeKey": "TW89DE",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Brentford",
    "name": "Currys - Brentford",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.485179,
    "lon": -0.323313,
    "adminDistrict": "Hounslow",
    "county": "",
    "country": "England"
  },
  {
    "id": "CT102QW-14",
    "region": "South East",
    "postcode": "CT10 2QW",
    "postcodeKey": "CT102QW",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Thanet",
    "name": "Currys - Thanet",
    "visitsPerQuarter": 6,
    "status": "Attack",
    "sdStore": "No",
    "lat": 51.3574,
    "lon": 1.400858,
    "adminDistrict": "Thanet",
    "county": "Kent",
    "country": "England"
  },
  {
    "id": "TN23EW-15",
    "region": "South East",
    "postcode": "TN2 3EW",
    "postcodeKey": "TN23EW",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Tunbridge Wells",
    "name": "Currys - Tunbridge Wells",
    "visitsPerQuarter": 6,
    "status": "Attack",
    "sdStore": "No",
    "lat": 51.157759,
    "lon": 0.292874,
    "adminDistrict": "Tunbridge Wells",
    "county": "Kent",
    "country": "England"
  },
  {
    "id": "UB33EX-16",
    "region": "South East",
    "postcode": "UB3 3EX",
    "postcodeKey": "UB33EX",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Hayes",
    "name": "Currys - Hayes",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.516451,
    "lon": -0.405558,
    "adminDistrict": "Hillingdon",
    "county": "",
    "country": "England"
  },
  {
    "id": "ME207TP-17",
    "region": "South East",
    "postcode": "ME20 7TP",
    "postcodeKey": "ME207TP",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Maidstone",
    "name": "Currys - Maidstone",
    "visitsPerQuarter": 6,
    "status": "Attack",
    "sdStore": "No",
    "lat": 51.293971,
    "lon": 0.469851,
    "adminDistrict": "Tonbridge and Malling",
    "county": "Kent",
    "country": "England"
  },
  {
    "id": "SE78LU-18",
    "region": "South East",
    "postcode": "SE7 8LU",
    "postcodeKey": "SE78LU",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Charlton",
    "name": "Currys - Charlton",
    "visitsPerQuarter": 6,
    "status": "Attack",
    "sdStore": "No",
    "lat": 51.489839,
    "lon": 0.034616,
    "adminDistrict": "Greenwich",
    "county": "",
    "country": "England"
  },
  {
    "id": "RG20QG-19",
    "region": "South East",
    "postcode": "RG2 0QG",
    "postcodeKey": "RG20QG",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Reading",
    "name": "Currys - Reading",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.423228,
    "lon": -0.98068,
    "adminDistrict": "Reading",
    "county": "",
    "country": "England"
  },
  {
    "id": "SW21BZ-20",
    "region": "South East",
    "postcode": "SW2 1BZ",
    "postcodeKey": "SW21BZ",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Brixton",
    "name": "Currys - Brixton",
    "visitsPerQuarter": 6,
    "status": "Attack",
    "sdStore": "No",
    "lat": 51.458433,
    "lon": -0.114157,
    "adminDistrict": "Lambeth",
    "county": "",
    "country": "England"
  },
  {
    "id": "BN229PW-21",
    "region": "South East",
    "postcode": "BN22 9PW",
    "postcodeKey": "BN229PW",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Eastbourne",
    "name": "Currys - Eastbourne",
    "visitsPerQuarter": 4,
    "status": "Defend",
    "sdStore": "No",
    "lat": 50.792096,
    "lon": 0.280069,
    "adminDistrict": "Eastbourne",
    "county": "East Sussex",
    "country": "England"
  },
  {
    "id": "TN237DH-22",
    "region": "South East",
    "postcode": "TN23 7DH",
    "postcodeKey": "TN237DH",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Ashford",
    "name": "Currys - Ashford",
    "visitsPerQuarter": 4,
    "status": "Defend",
    "sdStore": "No",
    "lat": 51.135176,
    "lon": 0.870752,
    "adminDistrict": "Ashford",
    "county": "Kent",
    "country": "England"
  },
  {
    "id": "CT11WZ-23",
    "region": "South East",
    "postcode": "CT1 1WZ",
    "postcodeKey": "CT11WZ",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Canterbury",
    "name": "Currys - Canterbury",
    "visitsPerQuarter": 4,
    "status": "Defend",
    "sdStore": "No",
    "lat": 51.293852,
    "lon": 1.105957,
    "adminDistrict": "Canterbury",
    "county": "Kent",
    "country": "England"
  },
  {
    "id": "DA14LD-24",
    "region": "South East",
    "postcode": "DA1 4LD",
    "postcodeKey": "DA14LD",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Crayford",
    "name": "Currys - Crayford",
    "visitsPerQuarter": 4,
    "status": "Defend",
    "sdStore": "No",
    "lat": 51.451254,
    "lon": 0.181465,
    "adminDistrict": "Bexley",
    "county": "",
    "country": "England"
  },
  {
    "id": "SW192PP-25",
    "region": "South East",
    "postcode": "SW19 2PP",
    "postcodeKey": "SW192PP",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Colliers Wood",
    "name": "Currys - Colliers Wood",
    "visitsPerQuarter": 4,
    "status": "Defend",
    "sdStore": "No",
    "lat": 51.416182,
    "lon": -0.178873,
    "adminDistrict": "Merton",
    "county": "",
    "country": "England"
  },
  {
    "id": "BN149FB-26",
    "region": "South East",
    "postcode": "BN14 9FB",
    "postcodeKey": "BN149FB",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Worthing",
    "name": "Currys - Worthing",
    "visitsPerQuarter": 4,
    "status": "Defend",
    "sdStore": "No",
    "lat": 50.835951,
    "lon": -0.364945,
    "adminDistrict": "Worthing",
    "county": "West Sussex",
    "country": "England"
  },
  {
    "id": "PO197YH-27",
    "region": "South East",
    "postcode": "PO19 7YH",
    "postcodeKey": "PO197YH",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Chichester",
    "name": "Currys - Chichester",
    "visitsPerQuarter": 4,
    "status": "Defend",
    "sdStore": "No",
    "lat": 50.841177,
    "lon": -0.756765,
    "adminDistrict": "Chichester",
    "county": "West Sussex",
    "country": "England"
  },
  {
    "id": "HA40EL-28",
    "region": "South East",
    "postcode": "HA4 0EL",
    "postcodeKey": "HA40EL",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "South Ruislip",
    "name": "Currys - South Ruislip",
    "visitsPerQuarter": 4,
    "status": "Defend",
    "sdStore": "No",
    "lat": 51.556442,
    "lon": -0.386647,
    "adminDistrict": "Hillingdon",
    "county": "",
    "country": "England"
  },
  {
    "id": "CT195GA-29",
    "region": "South East",
    "postcode": "CT19 5GA",
    "postcodeKey": "CT195GA",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Folkestone",
    "name": "Currys - Folkestone",
    "visitsPerQuarter": 4,
    "status": "Defend",
    "sdStore": "No",
    "lat": 51.095089,
    "lon": 1.165791,
    "adminDistrict": "Folkestone and Hythe",
    "county": "Kent",
    "country": "England"
  },
  {
    "id": "SE264PR-30",
    "region": "South East",
    "postcode": "SE26 4PR",
    "postcodeKey": "SE264PR",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Sydenham",
    "name": "Currys - Sydenham",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.431048,
    "lon": -0.033657,
    "adminDistrict": "Lewisham",
    "county": "",
    "country": "England"
  },
  {
    "id": "KT130XR-31",
    "region": "South East",
    "postcode": "KT13 0XR",
    "postcodeKey": "KT130XR",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Weybridge",
    "name": "Currys - Weybridge",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.345844,
    "lon": -0.474335,
    "adminDistrict": "Elmbridge",
    "county": "Surrey",
    "country": "England"
  },
  {
    "id": "BR53SR-32",
    "region": "South East",
    "postcode": "BR5 3SR",
    "postcodeKey": "BR53SR",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Orpington",
    "name": "Currys - Orpington",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.395601,
    "lon": 0.112947,
    "adminDistrict": "Bromley",
    "county": "",
    "country": "England"
  },
  {
    "id": "TN402JS-33",
    "region": "South East",
    "postcode": "TN40 2JS",
    "postcodeKey": "TN402JS",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Bexhill",
    "name": "Currys - Bexhill",
    "visitsPerQuarter": 0,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 50.844874,
    "lon": 0.501216,
    "adminDistrict": "Rother",
    "county": "East Sussex",
    "country": "England"
  },
  {
    "id": "W1T7NE-34",
    "region": "South East",
    "postcode": "W1T 7NE",
    "postcodeKey": "W1T7NE",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Tottenham Court Road",
    "name": "Currys - Tottenham Court Road",
    "visitsPerQuarter": 0,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.523897,
    "lon": -0.137056,
    "adminDistrict": "Camden",
    "county": "",
    "country": "England"
  },
  {
    "id": "TW136JH-35",
    "region": "South East",
    "postcode": "TW13 6JH",
    "postcodeKey": "TW136JH",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Hanworth",
    "name": "Currys - Hanworth",
    "visitsPerQuarter": 0,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.436544,
    "lon": -0.38122,
    "adminDistrict": "Hounslow",
    "county": "",
    "country": "England"
  },
  {
    "id": "HA98TS-36",
    "region": "South East",
    "postcode": "HA9 8TS",
    "postcodeKey": "HA98TS",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Wembley Stadium",
    "name": "Currys - Wembley Stadium",
    "visitsPerQuarter": 0,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.561251,
    "lon": -0.280711,
    "adminDistrict": "Brent",
    "county": "",
    "country": "England"
  },
  {
    "id": "W85ED-37",
    "region": "South East",
    "postcode": "W8 5ED",
    "postcodeKey": "W85ED",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Kensington",
    "name": "Currys - Kensington",
    "visitsPerQuarter": 0,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.502066,
    "lon": -0.189515,
    "adminDistrict": "Kensington and Chelsea",
    "county": "",
    "country": "England"
  },
  {
    "id": "BN175RA-38",
    "region": "South East",
    "postcode": "BN17 5RA",
    "postcodeKey": "BN175RA",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Littlehampton",
    "name": "Currys - Littlehampton",
    "visitsPerQuarter": 0,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 50.815337,
    "lon": -0.558727,
    "adminDistrict": "Arun",
    "county": "West Sussex",
    "country": "England"
  },
  {
    "id": "BR29LY-39",
    "region": "South East",
    "postcode": "BR2 9LY",
    "postcodeKey": "BR29LY",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Bromley",
    "name": "Currys - Bromley",
    "visitsPerQuarter": 0,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.396195,
    "lon": 0.026864,
    "adminDistrict": "Bromley",
    "county": "",
    "country": "England"
  },
  {
    "id": "W1D1BZ-40",
    "region": "South East",
    "postcode": "W1D 1BZ",
    "postcodeKey": "W1D1BZ",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "Oxford Street East",
    "name": "Currys - Oxford Street East",
    "visitsPerQuarter": 0,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.516178,
    "lon": -0.135122,
    "adminDistrict": "Westminster",
    "county": "",
    "country": "England"
  },
  {
    "id": "W127HT-41",
    "region": "South East",
    "postcode": "W12 7HT",
    "postcodeKey": "W127HT",
    "retailerGroup": "Currys",
    "retailer": "Currys",
    "storeName": "White City Westfield",
    "name": "Currys - White City Westfield",
    "visitsPerQuarter": 0,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.510103,
    "lon": -0.221694,
    "adminDistrict": "Hammersmith and Fulham",
    "county": "",
    "country": "England"
  },
  {
    "id": "RG12BB-42",
    "region": "South East",
    "postcode": "RG1 2BB",
    "postcodeKey": "RG12BB",
    "retailerGroup": "JLP",
    "retailer": "John Lewis",
    "storeName": "Reading",
    "name": "John Lewis - Reading",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.455317,
    "lon": -0.972064,
    "adminDistrict": "Reading",
    "county": "",
    "country": "England"
  },
  {
    "id": "DA99SA-43",
    "region": "South East",
    "postcode": "DA9 9SA",
    "postcodeKey": "DA99SA",
    "retailerGroup": "JLP",
    "retailer": "John Lewis",
    "storeName": "Bluewater",
    "name": "John Lewis - Bluewater",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.44044,
    "lon": 0.271564,
    "adminDistrict": "Dartford",
    "county": "Kent",
    "country": "England"
  },
  {
    "id": "PO197YH-44",
    "region": "South East",
    "postcode": "PO19 7YH",
    "postcodeKey": "PO197YH",
    "retailerGroup": "JLP",
    "retailer": "John Lewis",
    "storeName": "Chichester HOME",
    "name": "John Lewis - Chichester HOME",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 50.841177,
    "lon": -0.756765,
    "adminDistrict": "Chichester",
    "county": "West Sussex",
    "country": "England"
  },
  {
    "id": "KT11TE-45",
    "region": "South East",
    "postcode": "KT1 1TE",
    "postcodeKey": "KT11TE",
    "retailerGroup": "JLP",
    "retailer": "John Lewis",
    "storeName": "Kingston-on-Thames",
    "name": "John Lewis - Kingston-on-Thames",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.411597,
    "lon": -0.306666,
    "adminDistrict": "Kingston upon Thames",
    "county": "",
    "country": "England"
  },
  {
    "id": "W1C1DX-46",
    "region": "South East",
    "postcode": "W1C 1DX",
    "postcodeKey": "W1C1DX",
    "retailerGroup": "JLP",
    "retailer": "John Lewis",
    "storeName": "London Oxford St",
    "name": "John Lewis - London Oxford St",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.515059,
    "lon": -0.145084,
    "adminDistrict": "Westminster",
    "county": "",
    "country": "England"
  },
  {
    "id": "SW1W8EL-47",
    "region": "South East",
    "postcode": "SW1W 8EL",
    "postcodeKey": "SW1W8EL",
    "retailerGroup": "JLP",
    "retailer": "John Lewis",
    "storeName": "London Sloane Sq Peter Jones",
    "name": "John Lewis - London Sloane Sq Peter Jones",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.492247,
    "lon": -0.158976,
    "adminDistrict": "Kensington and Chelsea",
    "county": "",
    "country": "England"
  },
  {
    "id": "W127FU-48",
    "region": "South East",
    "postcode": "W12 7FU",
    "postcodeKey": "W127FU",
    "retailerGroup": "JLP",
    "retailer": "John Lewis",
    "storeName": "London White City",
    "name": "John Lewis - London White City",
    "visitsPerQuarter": 3,
    "status": "SD",
    "sdStore": "Yes",
    "lat": 51.510392,
    "lon": -0.222345,
    "adminDistrict": "Hammersmith and Fulham",
    "county": "",
    "country": "England"
  },
  {
    "id": "BR11QW-49",
    "region": "South East",
    "postcode": "BR1 1QW",
    "postcodeKey": "BR11QW",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "Bromley",
    "name": "Richer Sounds - Bromley",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.40753,
    "lon": 0.016725,
    "adminDistrict": "Bromley",
    "county": "",
    "country": "England"
  },
  {
    "id": "KT138DL-50",
    "region": "South East",
    "postcode": "KT13 8DL",
    "postcodeKey": "KT138DL",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "Weybridge",
    "name": "Richer Sounds - Weybridge",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.371345,
    "lon": -0.462512,
    "adminDistrict": "Elmbridge",
    "county": "Surrey",
    "country": "England"
  },
  {
    "id": "RG17NE-51",
    "region": "South East",
    "postcode": "RG1 7NE",
    "postcodeKey": "RG17NE",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "Reading",
    "name": "Richer Sounds - Reading",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.455186,
    "lon": -0.981825,
    "adminDistrict": "Reading",
    "county": "",
    "country": "England"
  },
  {
    "id": "RG26UE-52",
    "region": "South East",
    "postcode": "RG2 6UE",
    "postcodeKey": "RG26UE",
    "retailerGroup": "Costco",
    "retailer": "Costco",
    "storeName": "Reading",
    "name": "Costco - Reading",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.420713,
    "lon": -0.984115,
    "adminDistrict": "Wokingham",
    "county": "",
    "country": "England"
  },
  {
    "id": "ME141PL-53",
    "region": "South East",
    "postcode": "ME14 1PL",
    "postcodeKey": "ME141PL",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "Maidstone",
    "name": "Richer Sounds - Maidstone",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.274797,
    "lon": 0.522134,
    "adminDistrict": "Maidstone",
    "county": "Kent",
    "country": "England"
  },
  {
    "id": "TN49NT-54",
    "region": "South East",
    "postcode": "TN4 9NT",
    "postcodeKey": "TN49NT",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "Tunbridge Wells",
    "name": "Richer Sounds - Tunbridge Wells",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.138236,
    "lon": 0.262285,
    "adminDistrict": "Tunbridge Wells",
    "county": "Kent",
    "country": "England"
  },
  {
    "id": "GU146FE-55",
    "region": "South East",
    "postcode": "GU14 6FE",
    "postcodeKey": "GU146FE",
    "retailerGroup": "Costco",
    "retailer": "Costco",
    "storeName": "Farnborough",
    "name": "Costco - Farnborough",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.28223,
    "lon": -0.768169,
    "adminDistrict": "Rushmoor",
    "county": "Hampshire",
    "country": "England"
  },
  {
    "id": "GU12AF-56",
    "region": "South East",
    "postcode": "GU1 2AF",
    "postcodeKey": "GU12AF",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "Guildford",
    "name": "Richer Sounds - Guildford",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.238362,
    "lon": -0.565176,
    "adminDistrict": "Guildford",
    "county": "Surrey",
    "country": "England"
  },
  {
    "id": "CR01BG-57",
    "region": "South East",
    "postcode": "CR0 1BG",
    "postcodeKey": "CR01BG",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "Croydon",
    "name": "Richer Sounds - Croydon",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.364477,
    "lon": -0.098597,
    "adminDistrict": "Croydon",
    "county": "",
    "country": "England"
  },
  {
    "id": "CR04RR-58",
    "region": "South East",
    "postcode": "CR0 4RR",
    "postcodeKey": "CR04RR",
    "retailerGroup": "Costco",
    "retailer": "Costco",
    "storeName": "Croydon",
    "name": "Costco - Croydon",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.357178,
    "lon": -0.120559,
    "adminDistrict": "Croydon",
    "county": "",
    "country": "England"
  },
  {
    "id": "BN14JE-59",
    "region": "South East",
    "postcode": "BN1 4JE",
    "postcodeKey": "BN14JE",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "Brighton London Rd",
    "name": "Richer Sounds - Brighton London Rd",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 50.832899,
    "lon": -0.138371,
    "adminDistrict": "Brighton and Hove",
    "county": "",
    "country": "England"
  },
  {
    "id": "SL46BD-60",
    "region": "South East",
    "postcode": "SL4 6BD",
    "postcodeKey": "SL46BD",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "Eton",
    "name": "Richer Sounds - Eton",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.487952,
    "lon": -0.608809,
    "adminDistrict": "Windsor and Maidenhead",
    "county": "",
    "country": "England"
  },
  {
    "id": "RH121LP-61",
    "region": "South East",
    "postcode": "RH12 1LP",
    "postcodeKey": "RH121LP",
    "retailerGroup": "JLP",
    "retailer": "John Lewis",
    "storeName": "Horsham HOME",
    "name": "John Lewis - Horsham HOME",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.063101,
    "lon": -0.335648,
    "adminDistrict": "Horsham",
    "county": "West Sussex",
    "country": "England"
  },
  {
    "id": "KT25EL-62",
    "region": "South East",
    "postcode": "KT2 5EL",
    "postcodeKey": "KT25EL",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "Kingston-u-Thames",
    "name": "Richer Sounds - Kingston-u-Thames",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.415442,
    "lon": -0.300771,
    "adminDistrict": "Kingston upon Thames",
    "county": "",
    "country": "England"
  },
  {
    "id": "SE12TH-63",
    "region": "South East",
    "postcode": "SE1 2TH",
    "postcodeKey": "SE12TH",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "London Bridge",
    "name": "Richer Sounds - London Bridge",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.504258,
    "lon": -0.082453,
    "adminDistrict": "Southwark",
    "county": "",
    "country": "England"
  },
  {
    "id": "SW109EL-64",
    "region": "South East",
    "postcode": "SW10 9EL",
    "postcodeKey": "SW109EL",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "London Chelsea",
    "name": "Richer Sounds - London Chelsea",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.484554,
    "lon": -0.184059,
    "adminDistrict": "Kensington and Chelsea",
    "county": "",
    "country": "England"
  },
  {
    "id": "W45TT-65",
    "region": "South East",
    "postcode": "W4 5TT",
    "postcodeKey": "W45TT",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "London Chiswick",
    "name": "Richer Sounds - London Chiswick",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.492975,
    "lon": -0.268171,
    "adminDistrict": "Hounslow",
    "county": "",
    "country": "England"
  },
  {
    "id": "WC1A2SL-66",
    "region": "South East",
    "postcode": "WC1A 2SL",
    "postcodeKey": "WC1A2SL",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "London Holborn",
    "name": "Richer Sounds - London Holborn",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.517427,
    "lon": -0.124362,
    "adminDistrict": "Camden",
    "county": "",
    "country": "England"
  },
  {
    "id": "NW35DN-67",
    "region": "South East",
    "postcode": "NW3 5DN",
    "postcodeKey": "NW35DN",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "London Swiss Cottage",
    "name": "Richer Sounds - London Swiss Cottage",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.54456,
    "lon": -0.175266,
    "adminDistrict": "Camden",
    "county": "",
    "country": "England"
  },
  {
    "id": "RH27AQ-68",
    "region": "South East",
    "postcode": "RH2 7AQ",
    "postcodeKey": "RH27AQ",
    "retailerGroup": "Richer Sounds",
    "retailer": "Richer Sounds",
    "storeName": "Reigate",
    "name": "Richer Sounds - Reigate",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.235923,
    "lon": -0.20455,
    "adminDistrict": "Reigate and Banstead",
    "county": "Surrey",
    "country": "England"
  },
  {
    "id": "UB25XJ-69",
    "region": "South East",
    "postcode": "UB2 5XJ",
    "postcodeKey": "UB25XJ",
    "retailerGroup": "Costco",
    "retailer": "Costco",
    "storeName": "London Hayes",
    "name": "Costco - London Hayes",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.496116,
    "lon": -0.407953,
    "adminDistrict": "Hounslow",
    "county": "",
    "country": "England"
  },
  {
    "id": "TW165LN-70",
    "region": "South East",
    "postcode": "TW16 5LN",
    "postcodeKey": "TW165LN",
    "retailerGroup": "Costco",
    "retailer": "Costco",
    "storeName": "Sunbury-on-Thames",
    "name": "Costco - Sunbury-on-Thames",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.421409,
    "lon": -0.416015,
    "adminDistrict": "Spelthorne",
    "county": "Surrey",
    "country": "England"
  },
  {
    "id": "HA90YJ-71",
    "region": "South East",
    "postcode": "HA9 0YJ",
    "postcodeKey": "HA90YJ",
    "retailerGroup": "Costco",
    "retailer": "Costco",
    "storeName": "Wembley",
    "name": "Costco - Wembley",
    "visitsPerQuarter": 2,
    "status": "Maintain",
    "sdStore": "No",
    "lat": 51.558099,
    "lon": -0.27304,
    "adminDistrict": "Brent",
    "county": "",
    "country": "England"
  },
  {
    "id": "TN49NT-72",
    "region": "South East",
    "postcode": "TN4 9NT",
    "postcodeKey": "TN49NT",
    "retailerGroup": "Indies",
    "retailer": "Sevenoaks",
    "storeName": "Tunbridge Wells",
    "name": "Sevenoaks - Tunbridge Wells",
    "visitsPerQuarter": 1,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.138236,
    "lon": 0.262285,
    "adminDistrict": "Tunbridge Wells",
    "county": "Kent",
    "country": "England"
  },
  {
    "id": "GU14AW-73",
    "region": "South East",
    "postcode": "GU1 4AW",
    "postcodeKey": "GU14AW",
    "retailerGroup": "Indies",
    "retailer": "Sevenoaks",
    "storeName": "Guildford",
    "name": "Sevenoaks - Guildford",
    "visitsPerQuarter": 1,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.236705,
    "lon": -0.572333,
    "adminDistrict": "Guildford",
    "county": "Surrey",
    "country": "England"
  },
  {
    "id": "RH109JY-74",
    "region": "South East",
    "postcode": "RH10 9JY",
    "postcodeKey": "RH109JY",
    "retailerGroup": "Indies",
    "retailer": "Indies",
    "storeName": "Avensys - Crawley",
    "name": "Indies - Avensys - Crawley",
    "visitsPerQuarter": 1,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.134686,
    "lon": -0.173087,
    "adminDistrict": "Crawley",
    "county": "West Sussex",
    "country": "England"
  },
  {
    "id": "KT174QJ-75",
    "region": "South East",
    "postcode": "KT17 4QJ",
    "postcodeKey": "KT174QJ",
    "retailerGroup": "Indies",
    "retailer": "Sevenoaks",
    "storeName": "Epsom",
    "name": "Sevenoaks - Epsom",
    "visitsPerQuarter": 1,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.334202,
    "lon": -0.261525,
    "adminDistrict": "Epsom and Ewell",
    "county": "Surrey",
    "country": "England"
  },
  {
    "id": "BN411AG-76",
    "region": "South East",
    "postcode": "BN41 1AG",
    "postcodeKey": "BN411AG",
    "retailerGroup": "Indies",
    "retailer": "Indies",
    "storeName": "Hills Sound & Vision - Brighton",
    "name": "Indies - Hills Sound & Vision - Brighton",
    "visitsPerQuarter": 1,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 50.832754,
    "lon": -0.207792,
    "adminDistrict": "Brighton and Hove",
    "county": "",
    "country": "England"
  },
  {
    "id": "BN31JD-77",
    "region": "South East",
    "postcode": "BN3 1JD",
    "postcodeKey": "BN31JD",
    "retailerGroup": "Indies",
    "retailer": "Sevenoaks",
    "storeName": "Hove",
    "name": "Sevenoaks - Hove",
    "visitsPerQuarter": 1,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 50.825837,
    "lon": -0.16093,
    "adminDistrict": "Brighton and Hove",
    "county": "",
    "country": "England"
  },
  {
    "id": "KT11TX-78",
    "region": "South East",
    "postcode": "KT1 1TX",
    "postcodeKey": "KT11TX",
    "retailerGroup": "Indies",
    "retailer": "Bentalls",
    "storeName": "Kingston-on-Thames",
    "name": "Bentalls - Kingston-on-Thames",
    "visitsPerQuarter": 1,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.411717,
    "lon": -0.304993,
    "adminDistrict": "Kingston upon Thames",
    "county": "",
    "country": "England"
  },
  {
    "id": "KT11SF-79",
    "region": "South East",
    "postcode": "KT1 1SF",
    "postcodeKey": "KT11SF",
    "retailerGroup": "Indies",
    "retailer": "Sevenoaks",
    "storeName": "Kingston-u-Thames",
    "name": "Sevenoaks - Kingston-u-Thames",
    "visitsPerQuarter": 1,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.412112,
    "lon": -0.301872,
    "adminDistrict": "Kingston upon Thames",
    "county": "",
    "country": "England"
  },
  {
    "id": "SW100LR-80",
    "region": "South East",
    "postcode": "SW10 0LR",
    "postcodeKey": "SW100LR",
    "retailerGroup": "Indies",
    "retailer": "Sevenoaks",
    "storeName": "London Chelsea",
    "name": "Sevenoaks - London Chelsea",
    "visitsPerQuarter": 1,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.482653,
    "lon": -0.178042,
    "adminDistrict": "Kensington and Chelsea",
    "county": "",
    "country": "England"
  },
  {
    "id": "RG12HG-81",
    "region": "South East",
    "postcode": "RG1 2HG",
    "postcodeKey": "RG12HG",
    "retailerGroup": "Indies",
    "retailer": "Sevenoaks",
    "storeName": "Reading Kings Walk",
    "name": "Sevenoaks - Reading Kings Walk",
    "visitsPerQuarter": 1,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.45463,
    "lon": -0.969633,
    "adminDistrict": "Reading",
    "county": "",
    "country": "England"
  },
  {
    "id": "TN131BH-82",
    "region": "South East",
    "postcode": "TN13 1BH",
    "postcodeKey": "TN131BH",
    "retailerGroup": "Indies",
    "retailer": "Sevenoaks",
    "storeName": "Sevenoaks",
    "name": "Sevenoaks - Sevenoaks",
    "visitsPerQuarter": 1,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 51.274477,
    "lon": 0.187591,
    "adminDistrict": "Sevenoaks",
    "county": "Kent",
    "country": "England"
  },
  {
    "id": "BN271AU-83",
    "region": "South East",
    "postcode": "BN27 1AU",
    "postcodeKey": "BN271AU",
    "retailerGroup": "Indies",
    "retailer": "Euronics Centre",
    "storeName": "Smythe & Barrie Ltd Hailsham",
    "name": "Euronics Centre - Smythe & Barrie Ltd Hailsham",
    "visitsPerQuarter": 1,
    "status": "Low value/volume",
    "sdStore": "No",
    "lat": 50.865248,
    "lon": 0.257145,
    "adminDistrict": "Wealden",
    "county": "East Sussex",
    "country": "England"
  }
];
